### PR TITLE
HAWKULAR-1275 Fix LiveMetricsCapture when provider is offline

### PR DESCRIPTION
**Pull request by lucasponce**
I didn't rescue properly the exceptions in my previous changes, so when provider is offline, invoking LiveMetrics fail in the UI.
On this way, exception is logged and empty data are shown (what is expected).

### CODE REVIEW

**Comment by lucasponce** [comment]
Note, this PR will depend on 
https://github.com/hawkular/hawkular-client-ruby/pull/254

**Comment by lucasponce** [comment]
@israel-hdez can you run the specs of the provider repo ?
I am having some issues like this https://paste.fedoraproject.org/paste/zzLRDc-YY7jRcm2t3GURlw
Perhaps something I missed.
I guess @jshaughn also tried with different result

**Comment by lucasponce** [comment]
Ok, I could update the spec/manage/bundler.d and it seems I can progress.
Thx @jshaughn for the tip.

**Comment by jshaughn** [comment]
LGTM, the spec failures are expected.

**Pull request merged**
