### PR TITLE
Consolidate this on the same feedid as other specs and re-record

### PR DESCRIPTION
**Pull request by jshaughn**
using same start/end times as other tests.

### CODE REVIEW

**Comment by josejulio** [comment]
@israel-hdez worked with docker-compose to have a quick way to do a live test (and cassette recording). 
On his testing scenario there were three feeds. 
For the middleware manager, a standalone server and a domain server. This is the reason one single feed wasn't enough.
@israel-hdez can you review? I suppose this a quick way to have less errors on the build (its already done), and we could add back these tests on a future PR.

**Comment by jshaughn** [comment]
Yes, I'm no expert with this stuff, I'm just plodding along trying to get our failures to 0.  I'm OK with any approach that gets us there.  Because I am running a server locally against which I try to do recordings, and so I have a single feed.  That is why I tried to consolidate.  Because the tests use a central helper to grab the start and end times I also needed to re-record this because it was using an older time setting.  All in all, I hate all of this stuff, so if you have a better way, let's do that.  Also, most of the remaining failures work against domains, I think, so we;re going to need mazz's stuff for domains, I think, to continue.  I'm currently working on middleware_server_entities_spec and I think that will be it for me.

**Comment by israel-hdez** [comment]
Well... AFAIK, the middleware manager is like a standalone server. So... if the MWM has all the entities as a WF server, I think we could just remove the need of that standalone server from the tests and use the MWM instead.

**Comment by israel-hdez** [comment]
For me, it's OK... Merging

**Pull request merged**
