### PR TITLE
Use inventory v4

### PR DESCRIPTION
**Pull request by josejulio**
Switching from inventory v3 to v4.

Pending:
- [x] Operations (#110)
- [x] ~Live metrics (the maps that are in manageiq core)~ No longer needed
- [x] Gem release

Depends on https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/173

### CODE REVIEW

**Comment by israel-hdez** [comment]
Merging to have a base to continue work.

**Comment by moolitayer** [comment]
@josejulio this should be gaprindashvili/no like the providers-kubernetes [PR](https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/173)?

Anything else to go along?

**Comment by josejulio** [comment]
@moolitayer We are in the middle of a big change, so we decided to work on an alternative fork (hence this PR is on israel-hdez/manageiq-providers-hawkular and not on manageiq/manageiq-providers-hawkular).
But yes, this is also gaprindashvili/no, we will update the gem and providers-kubernetes once we are ready to merge.

**Comment by moolitayer** [comment]
If master still has an older version then merging https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/173 was wrong and will lead to broken dependencies. Does it need to be reverted @josejulio ?

**Comment by josejulio** [comment]
https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/173 is not merged yet. I will close it to avoid any confusion and will re-open that PR once we are ready to merge

**Comment by josejulio** [comment]
@moolitayer to clarify, if the commit is on master, it needs to be reverted, sorry for the confusion.

**Comment by moolitayer** [comment]
> ManageIQ/manageiq-providers-kubernetes#173 is not merged yet. I will close it to avoid any confusion and will re-open that PR once we are ready to merge

Right wasn't merged yet, was waiting to see what happens with this PR.  Thanks for closing, sorry for the confusion.

**Pull request merged**
