### PR TITLE
Fix operations specs

### PR DESCRIPTION
**Pull request by josejulio**
@israel-hdez please take a look

### CODE REVIEW

**Comment by jshaughn** [comment]
The CI run shows more failures (84) than I see locally without the changes (83).  Are you new failures were not introduced?

**Comment by josejulio** [comment]
I think we are currently using hawkular-ruby-client `5.0.0pre1` to run the tests.
We need to update it to point to https://github.com/hawkular/hawkular-client-ruby or release a gem version an update.

**Comment by jshaughn** [comment]
@josejulio Yes, that's probably the reason.  Merge is OK by me, @israel-hdez.

**Comment by josejulio** [comment]
I got 55 failures when running this and https://github.com/israel-hdez/manageiq/pull/2

**Pull request merged**
